[package]
name = "mylang"
version = "0.1.0"
authors = ["Linus KÃ¤mmerer <l.kaemmerer@tu-braunschweig.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
simple_logger = "1.11.0"
